collage/config/routes.rb
Rails.application.routes.draw do
  # Pages
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  # Courses
  resources :courses
  get 'courses/new', to: 'courses#new'
  get 'courses/', to: 'courses#index'
  post 'course_enroll', to: 'courses#enroll'
  
  # Users
  resources :users
  
  # Account
  get 'login', to: 'accounts#new'
  post 'login', to: 'accounts#create'  
  delete 'logout', to: 'accounts#destroy'  
end

collage/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

collage/app/models/course.rb
class Course < ApplicationRecord
  validates :short_name, presence: true, length: { minimum: 3, maximum: 100 }
  validates :name, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 1000 } 

  has_many :course_users	
	has_many :users, through: :course_users
end

collage/app/models/course_user.rb
class CourseUser < ApplicationRecord
	belongs_to :course
	belongs_to :user
end

collage/app/models/user.rb
class User < ApplicationRecord    
  before_save { self.email = email.downcase }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name, 
            presence: true, 
            uniqueness: { case_sensitive: false }, 
            length: { minimum: 3, maximum: 25 }  
            
  validates :email, 
            presence: true, 
            uniqueness: { case_sensitive: false }, 
            length: { maximum: 105 },
            format: { with: VALID_EMAIL_REGEX }    

  has_secure_password(attribute = :password, validations: true)
  
  has_many :course_users  
  has_many :courses, through: :course_users  
end

collage/app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  # GET /login
  def new
    
  end

  # POST /login
  def create
	  user = User.find_by(email: params[:account][:email].downcase)
	
    if user && user.authenticate(params[:account][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
	  
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details"
      
      render 'new'
    end
  end

  # DELETE /logout
  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
	
    redirect_to root_path
  end  
end

collage/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  #
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  #
  def logged_in?
    !!current_user
  end
  
  #
  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
	  
      redirect_to root_path
    end
  end
end

collage/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  # GET /courses
  def index
   @courses = Course.all
  end
  
  # GET /courses/new
  def show
    @course = Course.find(params[:id])
  end
    
  # GET /courses/new
  def new
  
  end 
  
  # POST /course_enroll
  def enroll
    @course = Course.find(params[:course_id])
    
    if !current_user.courses.exists?(@course.id)
      current_user.courses << @course
      flash[:success] = "Student enroll successfully."
      
      redirect_to current_user
    else
      flash[:success] = "Something went wrong!"
      
      redirect_to root_path
    end
  end
end

collage/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # GET /
  def home
  
  end
  
  # GET /about 
  def about
  
  end
end

collage/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  # GET users
  def index 
    @students = User.all  
  end
  
  # GET /users/1
  def show
    @courses = @user.courses.all
  end
  
  # GET /users/new
  def new
    @user = User.new
  end
  
  # POST /users
  def create 
    @user = User.new(user_params)
	  
    if @user.save	  
      session[:user_id] = @user.id	
      flash[:success] = "Student was created successfully."
      
      redirect_to @user   
    else
      render :new
    end
  end
  
  # GET /user/1/edit
  def edit
    
  end
  
  # PUT /users/1
  def update    
    if @user.update(user_params)
		  flash[:notice] = "Your account information was successfully updated."
      
		  redirect_to user_path @user
		else
		  render 'edit'
		end
  end  
  
  # DELETE /users/1
	def destroy
		@user.destroy
		session[:user_id] = nil if @user == current_user
		flash[:notice] = "Account and all associated articles successfully deleted"
		
		redirect_to root_path
  end
  
private
 # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
	
	# Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end
	
	# Require same user for action
	def require_same_user
		if current_user != @user && !current_user.admin?
		  flash[:alert] = "You can only edit or delete your own profile."
		  
		  redirect_to @user
		end
	end
end

collage/app/helpers/accounts_helper.rb
module AccountsHelper
end

collage/app/helpers/application_helper.rb
module ApplicationHelper
end

collage/app/helpers/courses_helper.rb
module CoursesHelper
end

collage/app/helpers/pages_helper.rb
module PagesHelper
end

collage/app/helpers/users_helper.rb
module UsersHelper
end

collage/app/views/users/edit.html.erb
<div class="row">
  <div class="col s12">
    <h3 class="center-align">Edit Student</h3>
  </div>
  
  <div class="col s12">
    <%= render 'share/errors', obj: @user %>
  </div>
  
  <div class="col s12">
    
    <%= form_with model: @user, local: true, method: "put" do |f| %>    
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :name %>
          <%= label_tag(:name) %>
        </div>
      </div>
      
      <div class="row">
        <div class="input-field col s12">
          <%= f.email_field :email %>
          <%= label_tag(:email) %>
        </div>
      </div>
      
      <div class="row">
        <div class="input-field col s12">
          <%= submit_tag("Update", class: "waves-effect waves-light btn") %>
        </div>
      </div>     
    <% end %> 
  
  </div>  
</div>

collage/app/views/users/index.html.erb
<div class="row">
  <div class="col s12">
    <h3 class="center-align">Students List</h3>
  </div>
  
  <div class="col s12">
  
  <div class="row">    
    <% @students.each do |student| %>
    <div class="col s12 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Name: <%= student.name %></span>
          <span class="card-title">Email: <%= student.email %></span>
          <div class="card-content white-text">
            <ul>
              <% student.courses.each do |course| %>
                <li><%= link_to course.name, course_path(course) %></li>
              <% end %>         
            </ul>
          </div>
        </div>
        <div class="card-action">
          <%= link_to 'Profile', user_path(student) %>        
        </div>
      </div>
    </div>
    <%end %>  
  </div>
  
  </div>  
</div>

collage/app/views/users/new.html.erb
<div class="row">
  <div class="col s12">
    <h3 class="center-align">New Student</h3>
  </div>
  
  <div class="col s12">
    <%= render 'share/errors', obj: @user %>
  </div>
  
  <div class="col s12">
    
    <%= form_with model: @user, local: true, method: "post" do |f| %>    
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :name %>
          <%= label_tag(:name) %>
        </div>
      </div>
      
      <div class="row">
        <div class="input-field col s12">
          <%= f.email_field :email %>
          <%= label_tag(:email) %>
        </div>
      </div>
      
      <div class="row">        
        <div class="input-field col s12"> 
          <%= f.password_field :password %>
          <%= label_tag(:password) %>
        </div>        
      </div>
      
      <div class="row">        
        <div class="input-field col s12"> 
          <%= f.password_field :password_confirmation %>
          <%= label_tag(:password_confirmation) %>
        </div>        
      </div>
      
      <div class="row">
        <div class="input-field col s12">
          <%= submit_tag("Sign up!", class: "waves-effect waves-light btn") %>
        </div>
      </div>     
    <% end %> 
  
  </div>  
</div>

collage/app/views/users/show.html.erb
<div class="row">
  <div class="col s12">
    <h3 class="center-align">Student Profile</h3>
  </div>

  <div class="col s12">

  <div class="row">
    <div class="col s12 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Name: <%= @user.name %></span>
          <span class="card-title">Email: <%= @user.email %></span>          
        </div>
        <div class="card-content white-text">
          <ul>
            <% @courses.each do |course| %>
              <li><%= link_to course.name, course_path(course) %></li>
            <% end %>         
          </ul>
        </div>
        <div class="card-action">
          <% if @user == current_user %>
            <%= link_to 'Edit', edit_user_path(@user) %>        
          <% end %> 
        </div>
      </div>
    </div>
  </div>

  </div>  
</div>