mainstreet/config/routes.rb
Rails.application.routes.draw do
  # User_stocks
  resources :user_stocks, only: [:create, :destroy]
  
  # Welcome, Pages
  root 'welcome#index'
  
  # User, Auth, Devise
  devise_for :users
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  resources :users, only: [:show]
  
  # Stock
  get 'search_stock', to: 'stock#search'
  
  # Friendship
  resources :friendships, only: [:create, :destroy]
end

mainstreet/app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

mainstreet/app/models/stock.rb
class Stock < ApplicationRecord
  validates :name, :ticker, presence: true
  
  has_many :user_stocks
  has_many :users, through: :user_stocks
  
  #
  def self.new_lookup(ticker_symbol)    
    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
      secret_token: Rails.application.credentials.iex_client[:sandbox_api_secret],
      endpoint: 'https://sandbox.iexapis.com/v1'
    )

    begin
      new(ticker: ticker_symbol, 
          name: client.company(ticker_symbol).company_name, 
          last_price: client.price(ticker_symbol))
    rescue => exception
      return nil
    end
  end  
  
  #
  def self.check_db(ticker_symbol)
    where(ticker: ticker_symbol).first
  end
end

mainstreet/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable 
         
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  
  #
  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    
    return false unless stock
    
    stocks.where(id: stock.id).exists?    
  end
  
  #
  def under_stock_limit?
    stocks.count < 10
  end

  #
  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end
  
  #
  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    
    "Anonymous"
  end
  
  #
  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end
  
  #
  def not_friends_with?(id_of_friend)
    !self.friends.where(id: id_of_friend).exists?
  end
  
  #
  def self.search(param)
    param.strip!
        
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    
    return nil unless to_send_back
    
    to_send_back
  end
  
  #
  def self.first_name_matches(param)
    matches('first_name', param)
  end

  #
  def self.last_name_matches(param)
    matches('last_name', param)
  end
  
  #
  def self.email_matches(param)
    matches('email', param)
  end

  #
  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end
end

mainstreet/app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

mainstreet/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!  
  before_action :configure_permitted_parameters, if: :devise_controller?

protected
  #
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end  
end

mainstreet/app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  # POST /friendships
  def create
    friend = User.find(params[:friend])    
    current_user.friendships.build(friend_id: friend.id)
    
    if current_user.save
      flash[:notice] = "Following friend"
    else
      flash[:alert] = "There was something wrong with the tracking request"
    end
    
    redirect_to my_friends_path
  end

  # DELETE /friendship/1
  def destroy
    friendship = current_user.friendships.where(friend_id: params[:id]).first
    friendship.destroy
    
    flash[:notice] = "Stopped following"
    
    redirect_to my_friends_path
  end
end

mainstreet/app/controllers/stock_controller.rb
class StockController < ApplicationController
  # GET /search_stock
  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      
      if @stock
        respond_to do |format|
          format.js { render partial: 'stock/stock' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Please enter a valid symbol to search"
          
          format.js { render partial: 'layouts/messages' }
        end
      end    
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a symbol to search"
        
        format.js { render partial: 'layouts/messages' }
      end
    end
  end
end

mainstreet/app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  # POST /user_stocks
  def create
    stock = Stock.check_db(params[:ticker])
    
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])      
      stock.save
    end  
    
    @user_stock = UserStock.create(user: current_user, stock: stock)    
    flash[:notice] = "Stock #{stock.name} was successfully added to your portfolio"
    
    redirect_to my_portfolio_path
  end  
  
  # DELETE /user_stock/1
  def destroy
    stock = Stock.find(params[:id])
    
    user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first    
    user_stock.destroy
    
    flash[:notice] = "#{stock.ticker} was successfully removed from portfolio"
    
    redirect_to my_portfolio_path
  end
end

mainstreet/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users/1
  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end
  
  # GET /my_portfolio
  def my_portfolio
    @user = current_user    
    @tracked_stocks = current_user.stocks
  end
  
  # GET /my_friends
  def my_friends
    @friends = current_user.friends
  end
  
  # GET /search_friend
  def search
    if params[:friend].present?
      @friends = User.search(params[:friend])
      @friends = current_user.except_current_user(@friends)
      
      if @friends
        respond_to do |format|
          format.js { render partial: 'friendships/friend_result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Couldn't find user"
          
          format.js { render partial: 'layouts/messages' }
        end
      end    
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a friend name or email to search"
        
        format.js { render partial: 'layouts/messages' }
      end
    end
  end
end

mainstreet/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  # GET /
  def index
  
  end
end

mainstreet/app/helpers/friendships_helper.rb
module FriendshipsHelper
end

mainstreet/app/helpers/stock_helper.rb
module StockHelper
end

mainstreet/app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

mainstreet/app/helpers/welcome_helper.rb
module WelcomeHelper
end

mainstreet/app/views/friendships/_friend_result.html.erb
<% if @friends %>
  <div class="card card-header results-block">
    <table class="col-md-12">
      <tbody>
        <% @friends.each do |friend| %>
          <tr>
            <td><strong>Name: </strong> <%= friend.full_name %></td>
            <td><strong>Email: </strong> <%= friend.email %></td>
            <td><strong>Actions: </strong> 
              <%= link_to "View Profile", 
                          user_path(friend),
                          class: "btn btn-sm btn-success" %>
                          
              <% if current_user.not_friends_with?(friend.id) %>
                <%= link_to 'Follow friend?', 
                            friendships_path(friend: friend),
                            class: "btn btn-sm btn-success", 
                            method: :post %>
              <% else %>
                <span class="badge badge-secondar">
                  You are friends.
                </span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

mainstreet/app/views/friendships/_friend_result.js.erb
document.querySelector('#friend-results').innerHTML = '<%= j render 'friendships/friend_result.html' %>'

mainstreet/app/views/friendships/_list.html.erb
<div class="row">
  <div class="col-9">  
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Email</th>
          <th scope="col">First Name</th>
          <th scope="col">Last Name</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @friends.each do |friend| %>
          <tr>
            <td><%= friend.email %></td>
            <td><%= friend.first_name %></td>
            <td><%= friend.last_name %></td>                       
            <td><%= link_to 'View Profile', 
                            user_path(friend),
                            class: 'btn btn-sm btn-success' %>
                            
                <%= link_to 'Stop following', 
                            friendship_path(friend),
                            method: :delete, 
                            data: {confirm: 'Are you sure?'},
                            class: 'btn btn-sm btn-warning' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

mainstreet/app/views/stock/_list.html.erb
<div class="row">
  <div class="col-9">  
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Ticker</th>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @tracked_stocks.each do |stock| %>
          <tr>
            <th scope="row"><%= stock.ticker %></th>
            <td><%= stock.name %></td>
            <td><%= stock.last_price %></td>
            <td><% if current_user.can_track_stock?(stock.ticker) %>
                  <%= link_to 'Add to portfolio', 
                              user_stocks_path(user: current_user, ticker: stock.ticker),
                              class: "btn btn-xs btn-success", 
                              method: :post %>
                <% elsif current_user.id != @user.id %>
                  <span class="badge badge-secondary">
                    You are already tracking
                    <% if !current_user.under_stock_limit? %>
                      10 stocks
                    <% end %>
                    <% if current_user.stock_already_tracked?(stock.ticker) %>
                      this stock
                    <% end %>
                  </span>
                <% end %>
              <% if current_user.id == @user.id %>
                <%= link_to 'Remove', 
                            user_stock_path(stock), 
                            method: :delete, 
                            data: {confirm: 'Are you sure?'},
                            class: 'btn btn-sm btn-warning' %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

mainstreet/app/views/stock/_stock.html.erb
<div class="card card-header results-block">
  <strong>Symbol: </strong> <%= @stock.ticker %>
  <strong>Name: </strong> <%= @stock.name %>
  <strong>Price: </strong> <%= @stock.last_price %>
  
  <% if current_user.can_track_stock?(@stock.ticker) %>
      <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker),
                                    class: "btn btn-xs btn-success", method: :post %>
  <% else %>
    <span class="badge badge-secondary">
      You are already tracking
      <% if !current_user.under_stock_limit? %>
        10 stocks
      <% end %>
      <% if current_user.stock_already_tracked?(@stock.ticker) %>
        this stock
      <% end %>
    </span>
  <% end %>
</div>
  

mainstreet/app/views/stock/_stock.js.erb
document.querySelector('#results').innerHTML = '<%= j render 'stock/stock.html' %>' 

mainstreet/app/views/users/_form.html.erb
<%= form_tag search_stock_path, remote: true, method: :get do %>
  <div class="form-group row">
    <div class="col-sm-9 no-right-padding">
      <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg" %>
    </div>
    <div class="col-sm-3 no-left-padding">
      <%= button_tag type: :submit, class: "btn btn-success" do %>
        <%= fa_icon 'search 2x' %>
      <% end %>
    </div>
  </div>
<% end %>

mainstreet/app/views/users/_search.html.erb
<%= form_tag search_friend_path, remote: true, method: :get do %>
  <div class="form-group row">
    <div class="col-sm-9 no-right-padding">
      <%= text_field_tag :friend, params[:friend], placeholder: "Name or email", autofocus: true, class: "form-control form-control-lg" %>
    </div>
    <div class="col-sm-3 no-left-padding">
      <%= button_tag type: :submit, class: "btn btn-success" do %>
        <%= fa_icon 'search 2x' %>
      <% end %>
    </div>
  </div>
<% end %>

mainstreet/app/views/users/my_friends.html.erb
<h1>Friends</h1>

<div class='search-area'>
  <h3>Search Friends</h3>
  
  <%= render 'search' %>
</div> 

<div id="messages">

</div>

<div id="friend-results">

</div>

<% if !@friends.empty? %>
  <%= render 'friendships/list' %>
<% end %>

mainstreet/app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<div class='search-area'>
  <h3>Search Stocks</h3>
  
  <%= render 'form' %>
</div> 

<div id="messages">

</div>

<div id="results">

</div>

<% if !@tracked_stocks.empty? %>
  <%= render 'stock/list'%>
<% end %>

mainstreet/app/views/users/show.html.erb
<h2>User Details</h2>

<div class="card card-header results-block">
  <table class="col-md-12">
    <tbody>
      <tr>
        <td><strong>Name: </strong> <%= @user.full_name %></td>
        <td><strong>Email: </strong> <%= @user.email %></td>
        <td>
          <% if current_user.not_friends_with?(@user.id) %>
            <%= link_to 'Follow friend?', friendships_path(friend: @user),
                          class: "btn btn-sm btn-success", method: :post %>
          <% else %>
            <span class="badge badge-secondary">
              You are friends
            </span>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

<% if !@tracked_stocks.empty? %>
  <%= render 'stock/list'%>
<% else %>
  <p class='lead'>This user is not tracking any stocks</p>
<% end %>

<%= link_to 'Back', my_friends_path, class: "btn btn-primary" %>