blog/config/routes.rb
Rails.application.routes.draw do  
  # Page
  root 'pages#home'  
  get 'about', to: 'pages#about'

  # Article
  resources :articles  
  # resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  
  # User
  get 'signup', to: 'users#new'
  resources :users, except: [:new]    

  # Auth
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'  
  
  # Category 
  resources :categories, only: [:index, :show, :new, :create, :edit, :update]
end

blog/app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }  
  
  belongs_to :user
  
  has_many :article_categories  
  has_many :categories, through: :article_categories
end

blog/app/models/article_category.rb
class ArticleCategory < ApplicationRecord
	belongs_to :article

	belongs_to :category
end

blog/app/models/category.rb
class Category < ApplicationRecord
	validates :name, presence: true, length: { minimum: 3, maximum: 25 }
	validates_uniqueness_of :name	

	has_many :article_categories	
	has_many :articles, through: :article_categories
end

blog/app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
 
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :username, 
            presence: true, 
            uniqueness: { case_sensitive: false }, 
            length: { minimum: 3, maximum: 25 }  
            
  validates :email, 
            presence: true, 
            uniqueness: { case_sensitive: false }, 
            length: { maximum: 105 },
            format: { with: VALID_EMAIL_REGEX }  
			
  has_many :articles, dependent: :destroy

  has_secure_password(attribute = :password, validations: true) #(xxxx_digest)
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  #
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  #
  def logged_in?
    !!current_user
  end
  
  #
  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
	  
      redirect_to login_path
    end
  end
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  # GET /articles
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)	
  end

  # GET /articles/1
  def show
    # byebug
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # POST /articles
  def create
    @article = Article.new(article_params)
		
    @article.user = current_user 
    
    if @article.save	  
      flash[:notice] = "Article was created successfully."
      
      redirect_to @article
      #redirect_to article_path(@article)	
    else
        render :new 
    end
  end

  # GET /articles/1/edit
  def edit
    #@article = Article.find(params[:id])
  end

  # PATCH/PUT /articles/1
  def update
    #@article = Article.find(params[:id])	
    #if @article.update(params.require(:article).permit(:title, :description))
    
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render 'edit'
    end	
  end

  # DELETE /articles/1
  def destroy
    #@article = Article.find(params[:id])
    @article.destroy
	
    redirect_to articles_path
  end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description, category_ids: [])
    end
	
	# Require same user for action
	def require_same_user
		if current_user != @article.user && !current_user.admin?
		  flash[:alert] = "You can only edit or delete your own article"
		  
		  redirect_to @article
		end
	end
end

blog/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :set_category, only: [:show, :edit, :update]
	before_action :require_admin, except: [:index, :show]
  
	# GET /categories
	def index
		@categories = Category.paginate(page: params[:page], per_page: 5)
	end
	
	# GET /categories/1
	def show
		@articles = @category.articles.paginate(page: params[:page], per_page: 5)
	end	
	
	# GET /categories/new
	def new
		@category = Category.new
	end
	
	# POST /categories
	def create
		@category = Category.new(category_params)

		if @category.save
			flash[:notice] = "Category was created successfully"

			redirect_to categories_path
		else
			render 'new'
		end
	end
	
	# GET /categories/1/edit
  def edit
  
  end

	# PATCH/PUT /categories/1
	def update	
    if @category.update(category_params)
      flash[:notice] = "Category was updated successfully."
      
      redirect_to @category
    else
      render 'edit'
    end	
  end
	
private
	#
	def set_category
		@category = Category.find(params[:id])
	end
	
	#
	def category_params
		params.require(:category).permit(:name)
	end
	
	#
	def require_admin
		if !logged_in? || (logged_in? and !current_user.admin?)
			flash[:alert] = "Only admins can perform that action"

			redirect_to categories_path
		end
	end
end

blog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
	# GET /
	def home

	end

	# GET /about
	def about

	end
end

blog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController  
  # GET /login
  def new
  
  end

  # POST /login
  def create
	  user = User.find_by(email: params[:session][:email].downcase)
	
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
	  
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render 'new'
    end
  end

  # DELETE /logout
  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
	
    redirect_to root_path
  end  
end

blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
	# GET /users	
	def index
		@users = User.paginate(page: params[:page], per_page: 5)
	end
	
	# GET /users/1
	def show		
		@articles = @user.articles.paginate(page: params[:page], per_page: 5)
	end
 
	# GET /signup
	def new
		@user = User.new
	end
	
	# POST /users
	def create
		@user = User.new(user_params)
		
		if @user.save
		  session[:user_id] = @user.id		  
		  flash[:notice] = "Welcome #{@user.username}, you have successfully signed up."
		  
		  redirect_to user_path @user
		else
		  render 'new'
		end
	end

	# GET /users/1/edit
	def edit
		#@user = User.find(params[:id])
	end

	# PATCH/PUT /users/1
	def update		
		if @user.update(user_params)
		  flash[:notice] = "Your account information was successfully updated."
		  redirect_to user_path @user
		else
		  render 'edit'
		end
	end
	
	# DELETE /users/1
	def destroy
		@user.destroy
		session[:user_id] = nil if @user == current_user
		flash[:notice] = "Account and all associated articles successfully deleted"
		
		redirect_to articles_path
    end
  
private
	# Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
	
	# Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
	
	# Require same user for action
	def require_same_user
		if current_user != @user && !current_user.admin?
		  flash[:alert] = "You can only edit or delete your own profile."
		  
		  redirect_to @user
		end
	end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80})
    email_address = user.email.downcase
	size = options[:size]
	
    hash = Digest::MD5.hexdigest(email_address)    
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
	
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/helpers/categories_helper.rb
module CategoriesHelper
end

blog/app/views/articles/_article.html.erb
<div class="row justify-content-md-center">
  <div class="col-8 mt-4">
	<div class="card text-center shadow mb-5 bg-white rounded">
	  <div class="card-header font-italic">
	    <% if article.user %>
          by <%= link_to article.user.username, user_path(article.user) %>
        <% end %>
	  </div>
	  <div class="card-body">
		<h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
		<p class="card-text"><%= truncate(article.description, length: 100) %></p>
		<p class="card-text">		
		<% article.categories.each do |category| %>
			<%= render 'categories/category', category: category %>
		<% end %>		  
		</p>		
		<%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
		<% if logged_in? && (article.user == current_user || current_user.admin?) %>
		  <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
		  <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
	    <% end %>
	  </div>
	  <div class="card-footer text-muted">
		<small>Created <%= time_ago_in_words(article.created_at) %> ago, 
		edited <%= time_ago_in_words(article.updated_at) %> ago</small>
	  </div>
	</div>
  </div>
</div>
	

blog/app/views/articles/_form.html.erb
<div class="container">

<div class="row justify-content-center">
	<div class="col-10">	
	<%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
	  
	<div class="form-group row">
	  <%= f.label :title, class: "col-2 col-form-label text-light" %>
	  <div class="col-10">
		<%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
	  </div>
	</div>
		
	<div class="form-group row">
	  <%= f.label :description, class: "col-2 col-form-label text-light" %>
	  <div class="col-10"> 
		<%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
	  </div>
	</div>
				
	<div class="form-group row">
	  <div class="col-12 text-light">
		<%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
		  <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
		<% end %>
	  </div>
	</div>

	<div class="form-group row justify-content-center">
	  <%= f.submit(@article.new_record? ? "Create Article" : "Update Article", class: "btn btn-outline-light btn-lg") %>
    </div>
	  
    <% end %>    
	</div>
	
    <div class="mb-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
    </div>
</div>

</div>

blog/app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Editing Article</h1>

<%= render 'shared/errors', obj: @article %>

<%= render 'form' %>

blog/app/views/articles/index.html.erb
<h1 class="text-center mt-4">Articles</h1>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<div class="container">
  <% @articles.each do |article| %>
    <%= render 'article', article: article %>
  <% end %>
</div>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

blog/app/views/articles/new.html.erb
<h1 class="text-center mt-4">New Article</h1>

<%= render 'shared/errors', obj: @article %>

<%= render 'form' %>

blog/app/views/articles/show.html.erb
<h1 class="text-center mt-4">Article Detail</h1>

<div class="container">
<div class="row justify-content-md-center">
  <div class="col-8 mt-4">
	<div class="card text-center shadow mb-5 bg-white rounded">
	  <div class="card-header font-italic">		
		<% if @article.user %>
		  <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
	      by <%= link_to @article.user.username, user_path(@article.user) %>
		<% end %>
	  </div>
	  <div class="card-body">
		<div class="card-text text-left"><%= simple_format(@article.description) %></div>
		
		<div class="card-text text-left">
		  <% if @article.categories.any? %>
	        <span>Categories: </span>
			<% @article.categories.each do |category| %>
			  <%= link_to category.name, category_path(category) %>
			<% end %>
          <% end %>
        </div>	
		
		<% if logged_in? && (@article.user == current_user || current_user.admin?) %>
		  <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
		  <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
	    <% end %>
	  </div>
	  <div class="card-footer text-muted">
		<small>Created <%= time_ago_in_words(@article.created_at) %> ago, 
		edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
	  </div>
	</div>
  </div>
</div>
</div>

blog/app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; <%= Time.zone.now.year %> - ITsAli.com</small>
  </div>
</footer>

blog/app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div> 
	

blog/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "ITsAli.com BLOG", root_path, class: "navbar-brand", id: "logo" %> 
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">    
      <li class="nav-item">
         <%= link_to "About", about_path, class: "nav-link" %> 
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
		  <% if logged_in? %>
        <%= link_to "New Article", new_article_path, class: "dropdown-item" %>
		    <div class="dropdown-divider"></div> 			
		  <% end %>		  
        <%= link_to "Articles", articles_path, class: "dropdown-item" %>
        <div class="dropdown-divider"></div> 		  
		  <% if logged_in? and current_user.admin? %>
			<%= link_to "New Category", new_category_path, class: "dropdown-item" %>
			<div class="dropdown-divider"></div>      
		  <% end %>
		  
          <%= link_to "Categories", categories_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
        </div>
      </li>    
	  <li class="nav-item active">
	    <%= link_to "Users", users_path, class: "nav-link" %>       
      </li> 	  
	  <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View Profile", user_path(current_user), class: "dropdown-item" %>
			<div class="dropdown-divider"></div>   
            <%= link_to "Edit Profile", edit_user_path(current_user), class: "dropdown-item" %>
			<div class="dropdown-divider"></div>   
			<%= link_to "Delete Profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?" } %>
			<div class="dropdown-divider"></div>  
          </div>
        </li>		
        <li class="nav-item">
          <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log In', login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', signup_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ITsAli.com - Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
	
	<div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
	
	<%= render 'layouts/footer' %>
  </body>
</html>