galabata/config/routes.rb
Rails.application.routes.draw do
  # Chatroom
  root 'chatroom#index' 	
  
  # Auth
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  # Users
  resources :users
  
  # Messages
  post 'message', to: 'messages#create'
  
  # WebSocket - Channel'sCable
  mount ActionCable.server, at: '/cable'
end

galabata/app/models/message.rb
class Message < ApplicationRecord   
  validates :body, presence: true
  
  belongs_to :user
  
  scope :custom_display, -> { order(:created_at).last(20) }
end

galabata/app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, length: { minimum: 3, maximum: 15 }
  
  validates_uniqueness_of :username, case_sensitive: false
  
  has_many :messages, dependent: :destroy
  
  has_secure_password(attribute = :password, validations: true)
end

galabata/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  #
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  #
  def logged_in?
    !!current_user
  end

  #
  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to perform that action"
      
      redirect_to login_path
    end
  end
end

galabata/app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController  
  before_action :require_user
  
  # GET /
  def index
    @message = Message.new
    
    @messages = Message.custom_display    
  end 
end

galabata/app/controllers/messages_controller.rb
class MessagesController < ApplicationController  
  before_action :require_user
  
  # POST /message
  def create
    message = current_user.messages.build(message_params)
    
    if message.save
      ActionCable.server.broadcast "chatroom_channel",
                                    mod_message: message_render(message)      
    end
  end

private 
 
  #
  def message_params
    params.require(:message).permit(:body)
  end  
  
  #
  def message_render(message)
    render(partial: 'message', locals: {message: message})
  end
end

galabata/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]

  # GET /login
  def new
  
  end
  
  # POST /login
  def create
    user = User.find_by(username: params[:session][:username])
    
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      
      redirect_to root_path
    else
      flash.now[:error] = "There was something wrong with your login information"
      
      render 'new'
    end
  end

  # DELETE /logout
  def destroy
    session[:user_id] = nil
    flash[:success] = "You have successfully logged out"
    
    redirect_to login_path
  end
  
private

  #
  def logged_in_redirect
    if logged_in?
      flash[:error] = "You are already logged in"
      
      redirect_to root_path
    end
  end
end

galabata/app/controllers/users_controller.rb
class UsersController < ApplicationController

end

galabata/app/helpers/chatroom_helper.rb
module ChatroomHelper
end

galabata/app/helpers/messages_helper.rb
module MessagesHelper
end

galabata/app/helpers/sessions_helper.rb
module SessionsHelper
end

galabata/app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="circular orange coffee icon"></i>
  GalaBata
</h4>

<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content" id="messages">
        <div class="ui feed" id="message-container">
          <% @messages.each do |message| %>
            <%= render 'messages/message', message: message %>
          <% end %>  
        </div>
      </div>
      <div class="extra content">
        <%= form_for(@message, html: {class: "ui reply form", role: "form"}, url: message_path, remote: true) do |f| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= f.text_field :body %>
              <%= f.button '<i class="bordered inverted orange edit icon"></i>'.html_safe %>              
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui inverted vertical menu">
          <a class="active item">
            Home
          </a>
          <a class="item">
            Messages
          </a>
          <a class="item">
            Friends
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

galabata/app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
       <em><%= message.user.username %></em>: <%= message.body %>
    </div>
  </div>
</div>
          